DEBUG 2020-12-23 16:16:40.894 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-23 16:16:40.894 UTC: 	 Running on: Linux lxplus715.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-23 16:16:40.894 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-23 16:16:40.894 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
INFO 2020-12-23 16:16:40.895 UTC: 	 Will use CRAB configuration file submit_on_crab.py
DEBUG 2020-12-23 16:16:40.895 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-23 16:16:40.932 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2020-12-23 16:16:40.932 UTC: 	 Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_MCProductionMINIAOD#REQUESTDATE##WHOAMI#' already exists 
Please change the requestName in the config file
ERROR 2020-12-23 16:16:40.932 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_MCProductionMINIAOD#REQUESTDATE##WHOAMI#' already exists 
Please change the requestName in the config file
INFO 2020-12-23 16:16:40.935 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2020-12-23 16:19:14.637 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-23 16:19:14.637 UTC: 	 Running on: Linux lxplus715.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-23 16:19:14.637 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-23 16:19:14.638 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
INFO 2020-12-23 16:19:14.639 UTC: 	 Will use CRAB configuration file submit_on_crab.py
DEBUG 2020-12-23 16:19:14.639 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-23 16:19:14.680 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2020-12-23 16:19:14.680 UTC: 	 Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec23' already exists 
Please change the requestName in the config file
ERROR 2020-12-23 16:19:14.681 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec23' already exists 
Please change the requestName in the config file
INFO 2020-12-23 16:19:14.683 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2020-12-23 16:21:32.476 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-23 16:21:32.477 UTC: 	 Running on: Linux lxplus715.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-23 16:21:32.477 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-23 16:21:32.477 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
INFO 2020-12-23 16:21:32.478 UTC: 	 Will use CRAB configuration file submit_on_crab.py
DEBUG 2020-12-23 16:21:32.478 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-23 16:21:32.569 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2020-12-23 16:21:32.570 UTC: 	 Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec23' already exists 
Please change the requestName in the config file
ERROR 2020-12-23 16:21:32.570 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec23' already exists 
Please change the requestName in the config file
INFO 2020-12-23 16:21:32.572 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2020-12-28 11:31:09.778 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-28 11:31:09.779 UTC: 	 Running on: Linux lxplus740.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-28 11:31:09.779 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-28 11:31:09.779 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
INFO 2020-12-28 11:31:09.780 UTC: 	 Will use CRAB configuration file submit_on_crab.py
DEBUG 2020-12-28 11:31:09.780 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-28 11:31:09.817 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2020-12-28 11:31:09.818 UTC: 	 Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec28' already exists 
Please change the requestName in the config file
ERROR 2020-12-28 11:31:09.818 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec28' already exists 
Please change the requestName in the config file
INFO 2020-12-28 11:31:09.822 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2020-12-28 12:02:26.147 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-28 12:02:26.148 UTC: 	 Running on: Linux lxplus740.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-28 12:02:26.148 UTC: 	 Executing command: 'purge'
DEBUG 2020-12-28 12:02:26.149 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
ERROR 2020-12-28 12:02:26.150 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction
ERROR 2020-12-28 12:02:26.150 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 632, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 494, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction
INFO 2020-12-28 12:02:26.151 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2020-12-28 13:42:36.783 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-28 13:42:36.783 UTC: 	 Running on: Linux lxplus717.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-28 13:42:36.783 UTC: 	 Executing command: 'status'
DEBUG 2020-12-28 13:42:36.785 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
ERROR 2020-12-28 13:42:36.803 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction
ERROR 2020-12-28 13:42:36.804 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 632, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 494, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction
INFO 2020-12-28 13:42:36.823 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2020-12-30 12:26:09.947 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-30 12:26:09.947 UTC: 	 Running on: Linux lxplus743.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-30 12:26:09.947 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-30 12:26:09.947 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
INFO 2020-12-30 12:26:09.949 UTC: 	 Will use CRAB configuration file submit_on_crab.py
DEBUG 2020-12-30 12:26:09.949 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-30 12:26:10.077 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2020-12-30 12:26:10.077 UTC: 	 Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec30' already exists 
Please change the requestName in the config file
ERROR 2020-12-30 12:26:10.077 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec30' already exists 
Please change the requestName in the config file
INFO 2020-12-30 12:26:10.096 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2020-12-30 15:30:28.755 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-30 15:30:28.756 UTC: 	 Running on: Linux lxplus786.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-30 15:30:28.756 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-30 15:30:28.757 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
INFO 2020-12-30 15:30:28.760 UTC: 	 Will use CRAB configuration file submit_on_crab.py
DEBUG 2020-12-30 15:30:28.760 UTC: 	 Loading CRAB configuration file.
ERROR 2020-12-30 15:30:29.022 UTC: 	 Error while loading CRAB configuration:
name 'cofig' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-12-30 15:30:29.023 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 312, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'cofig' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-12-30 15:30:29.045 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2020-12-30 15:31:35.774 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-30 15:31:35.774 UTC: 	 Running on: Linux lxplus786.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-30 15:31:35.774 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-30 15:31:35.774 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
INFO 2020-12-30 15:31:35.776 UTC: 	 Will use CRAB configuration file submit_on_crab.py
DEBUG 2020-12-30 15:31:35.777 UTC: 	 Loading CRAB configuration file.
ERROR 2020-12-30 15:31:35.845 UTC: 	 Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-12-30 15:31:35.846 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 312, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-12-30 15:31:35.854 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2020-12-30 16:44:37.538 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-30 16:44:37.538 UTC: 	 Running on: Linux lxplus756.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-30 16:44:37.538 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-30 16:44:37.539 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
INFO 2020-12-30 16:44:37.542 UTC: 	 Will use CRAB configuration file submit_on_crab.py
DEBUG 2020-12-30 16:44:37.543 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-30 16:44:37.713 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2020-12-30 16:44:37.734 UTC: 	 Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec30' already exists 
Please change the requestName in the config file
ERROR 2020-12-30 16:44:37.734 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec30' already exists 
Please change the requestName in the config file
INFO 2020-12-30 16:44:37.750 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2020-12-30 16:50:34.372 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-30 16:50:34.373 UTC: 	 Running on: Linux lxplus756.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-30 16:50:34.373 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-30 16:50:34.373 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
INFO 2020-12-30 16:50:34.375 UTC: 	 Will use CRAB configuration file submit_on_crab.py
DEBUG 2020-12-30 16:50:34.375 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-30 16:50:34.556 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2020-12-30 16:50:34.565 UTC: 	 Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec30' already exists 
Please change the requestName in the config file
ERROR 2020-12-30 16:50:34.565 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec30' already exists 
Please change the requestName in the config file
INFO 2020-12-30 16:50:34.578 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2020-12-30 18:28:42.705 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-30 18:28:42.706 UTC: 	 Running on: Linux lxplus785.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-30 18:28:42.706 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-30 18:28:42.706 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
INFO 2020-12-30 18:28:42.725 UTC: 	 Will use CRAB configuration file submit_on_crab.py
DEBUG 2020-12-30 18:28:42.725 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-30 18:28:42.881 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2020-12-30 18:28:42.944 UTC: 	 Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec30' already exists 
Please change the requestName in the config file
ERROR 2020-12-30 18:28:42.945 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab_privateMCProduction/crab_privateHNL_2020Dec30' already exists 
Please change the requestName in the config file
INFO 2020-12-30 18:28:43.012 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2021-01-02 11:14:15.687 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-02 11:14:15.688 UTC: 	 Running on: Linux lxplus780.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-02 11:14:15.688 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-02 11:14:15.689 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
INFO 2021-01-02 11:14:15.709 UTC: 	 Will use CRAB configuration file submit_on_crab.py
DEBUG 2021-01-02 11:14:15.709 UTC: 	 Loading CRAB configuration file.
INFO 2021-01-02 11:14:15.861 UTC: 	 Wrong format in command-line argument '--dryrun'. Expected format is <section-name>.<parameter-name>=<parameter-value>.
INFO 2021-01-02 11:14:15.862 UTC: 	 If the argument '--dryrun' is an option to the submit command, try 'crab submit --dryrun [value for --dryrun option (if required)] [arguments]'.
ERROR 2021-01-02 11:14:15.862 UTC: 	 ERROR: Wrong command-line format.
ERROR 2021-01-02 11:14:15.862 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 312, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 68, in loadConfig
    raise ConfigurationException("ERROR: Wrong command-line format.")
ConfigurationException: ERROR: Wrong command-line format.
INFO 2021-01-02 11:14:15.884 UTC: 	 Log file is /afs/cern.ch/work/r/ratramon/HNL/CMSSW_10_2_15/src/HNLsGen/crab/crab.log
DEBUG 2021-01-02 11:14:45.397 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-02 11:14:45.397 UTC: 	 Running on: Linux lxplus780.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-02 11:14:45.397 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-02 11:14:45.397 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ratramon/.crab3
